import {
  Document, Page, Text, View, StyleSheet,
} from '@react-pdf/renderer';

const DEPRECATED_BELOW = parseInt(process.env.NEXT_PUBLIC_DEPRECATED_BELOW_VERSION ?? '2022');
const DEADLINE = process.env.NEXT_PUBLIC_DEADLINE_DATE ?? '2026-05-07';

const styles = StyleSheet.create({
  page: { padding: 48, fontFamily: 'Helvetica', fontSize: 10, color: '#1a1a1a' },
  coverTitle: { fontSize: 24, fontFamily: 'Helvetica-Bold', marginBottom: 8 },
  coverSub: { fontSize: 12, color: '#666', marginBottom: 4 },
  sectionTitle: { fontSize: 13, fontFamily: 'Helvetica-Bold', marginBottom: 10, marginTop: 20, borderBottomWidth: 0.5, borderBottomColor: '#ddd', paddingBottom: 4 },
  kpiRow: { flexDirection: 'row', gap: 12, marginBottom: 16 },
  kpiBox: { flex: 1, backgroundColor: '#f8f8f8', borderRadius: 4, padding: 10 },
  kpiValue: { fontSize: 20, fontFamily: 'Helvetica-Bold', marginBottom: 2 },
  kpiLabel: { fontSize: 8, color: '#666', textTransform: 'uppercase' },
  table: { width: '100%', marginBottom: 12 },
  tableHeader: { flexDirection: 'row', backgroundColor: '#f0f0f0', padding: '5 8', marginBottom: 1 },
  tableRow: { flexDirection: 'row', padding: '5 8', borderBottomWidth: 0.5, borderBottomColor: '#eee' },
  th: { fontSize: 8, fontFamily: 'Helvetica-Bold', color: '#444', textTransform: 'uppercase' },
  td: { fontSize: 9 },
  badge: { fontSize: 8, paddingHorizontal: 5, paddingVertical: 2, borderRadius: 3 },
  badgeDanger: { backgroundColor: '#fee', color: '#c00' },
  badgeOk: { backgroundColor: '#efe', color: '#060' },
  footerText: { fontSize: 8, color: '#999', marginTop: 40, borderTopWidth: 0.5, borderTopColor: '#eee', paddingTop: 8 },
  projectHeader: { backgroundColor: '#f5f5f5', padding: '8 10', marginBottom: 6, borderRadius: 4, marginTop: 16 },
  projectName: { fontSize: 11, fontFamily: 'Helvetica-Bold' },
  projectMeta: { fontSize: 8, color: '#666', marginTop: 2 },
});

interface Project {
  id: string;
  name: string;
  project_type: string;
  member_count: number;
  at_risk_file_count: number;
  rvt_file_count: number;
  min_revit_version: string | null;
  priority_score: number;
  last_file_activity: string | null;
}

interface RevitFile {
  file_name: string;
  folder_path: string | null;
  revit_version: string | null;
  detection_method: string | null;
  is_composite: boolean;
}

interface ReportData {
  hubName: string;
  scanDate: string;
  totalProjects: number;
  atRiskProjects: Project[];
  filesPerProject: Record<string, RevitFile[]>;
  totalFiles: number;
  atRiskFiles: number;
  membersImpacted: number;
}

function daysUntil(dateStr: string) {
  return Math.max(0, Math.ceil((new Date(dateStr).getTime() - Date.now()) / 86400000));
}

function relDate(dateStr: string | null) {
  if (!dateStr) return '—';
  return new Date(dateStr).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
}

export function ScanReport({ data }: { data: ReportData }) {
  const daysLeft = daysUntil(DEADLINE);

  return (
    <Document>
      {/* Cover page */}
      <Page size="A4" style={styles.page}>
        <View style={{ marginTop: 80 }}>
          <Text style={styles.coverTitle}>Revit C4R Scanner</Text>
          <Text style={styles.coverTitle}>Upgrade Risk Report</Text>
          <Text style={[styles.coverSub, { marginTop: 16 }]}>{data.hubName}</Text>
          <Text style={styles.coverSub}>Scan date: {data.scanDate}</Text>
          <Text style={styles.coverSub}>Generated: {new Date().toLocaleDateString()}</Text>
        </View>

        <View style={{ marginTop: 60 }}>
          <View style={styles.kpiRow}>
            <View style={styles.kpiBox}>
              <Text style={[styles.kpiValue, { color: data.atRiskProjects.length > 0 ? '#c00' : '#333' }]}>
                {data.atRiskProjects.length}
              </Text>
              <Text style={styles.kpiLabel}>Projects at risk</Text>
            </View>
            <View style={styles.kpiBox}>
              <Text style={[styles.kpiValue, { color: data.atRiskFiles > 0 ? '#d97706' : '#333' }]}>
                {data.atRiskFiles}
              </Text>
              <Text style={styles.kpiLabel}>Files needing upgrade</Text>
            </View>
            <View style={styles.kpiBox}>
              <Text style={styles.kpiValue}>{data.membersImpacted}</Text>
              <Text style={styles.kpiLabel}>Members impacted</Text>
            </View>
            <View style={styles.kpiBox}>
              <Text style={[styles.kpiValue, { color: daysLeft < 14 ? '#c00' : '#333' }]}>{daysLeft}</Text>
              <Text style={styles.kpiLabel}>Days to deadline</Text>
            </View>
          </View>
        </View>

        <Text style={styles.footerText}>
          Files below Revit {DEPRECATED_BELOW} will lose cloud model access on {DEADLINE}.
          This report was generated by Revit C4R Scanner — open source at github.com.
        </Text>
      </Page>

      {/* Executive summary */}
      <Page size="A4" style={styles.page}>
        <Text style={styles.sectionTitle}>Executive Summary</Text>
        <Text style={{ marginBottom: 10, lineHeight: 1.5 }}>
          This report covers {data.totalProjects} projects in the {data.hubName} hub.
          {data.atRiskProjects.length} projects ({data.totalFiles > 0 ? Math.round(data.atRiskProjects.length / data.totalProjects * 100) : 0}%)
          contain Revit files on versions older than {DEPRECATED_BELOW}, which will lose cloud collaboration
          access on {DEADLINE}.
        </Text>
        <Text style={{ marginBottom: 10, lineHeight: 1.5 }}>
          {data.atRiskFiles} files across {data.atRiskProjects.length} projects require upgrading.
          {data.membersImpacted} team members across these projects will be impacted if files are not
          upgraded before the deadline.
        </Text>
        <Text style={{ lineHeight: 1.5 }}>
          Autodesk drops cloud model access for the oldest supported Revit version each year,
          approximately 30 days after the newest version is released. Files must be upgraded by
          opening them in a supported Revit version and saving back to the cloud.
        </Text>

        {/* At-risk projects table */}
        <Text style={styles.sectionTitle}>At-Risk Projects (sorted by priority score)</Text>
        <View style={styles.table}>
          <View style={styles.tableHeader}>
            {['Project', 'Type', 'Members', 'At-risk', 'Min version', 'Last active', 'Score'].map(h => (
              <Text key={h} style={[styles.th, { flex: h === 'Project' ? 3 : 1 }]}>{h}</Text>
            ))}
          </View>
          {data.atRiskProjects.map(p => (
            <View key={p.id} style={styles.tableRow}>
              <Text style={[styles.td, { flex: 3 }]}>{p.name}</Text>
              <Text style={[styles.td, { flex: 1 }]}>{p.project_type}</Text>
              <Text style={[styles.td, { flex: 1 }]}>{p.member_count}</Text>
              <Text style={[styles.td, { flex: 1, color: '#c00' }]}>{p.at_risk_file_count}</Text>
              <Text style={[styles.td, { flex: 1 }]}>{p.min_revit_version ?? '—'}</Text>
              <Text style={[styles.td, { flex: 1 }]}>{relDate(p.last_file_activity)}</Text>
              <Text style={[styles.td, { flex: 1 }]}>{p.priority_score}</Text>
            </View>
          ))}
        </View>
      </Page>

      {/* Per-project detail pages */}
      {data.atRiskProjects.filter(p => p.priority_score >= 50).map(p => {
        const pFiles = (data.filesPerProject[p.id] ?? []).filter(f =>
          f.revit_version && parseInt(f.revit_version) < DEPRECATED_BELOW
        );
        if (pFiles.length === 0) return null;

        return (
          <Page key={p.id} size="A4" style={styles.page}>
            <View style={styles.projectHeader}>
              <Text style={styles.projectName}>{p.name}</Text>
              <Text style={styles.projectMeta}>
                {p.project_type} · {p.member_count} members · {p.at_risk_file_count} at-risk files · Priority {p.priority_score}
              </Text>
            </View>

            <View style={styles.table}>
              <View style={styles.tableHeader}>
                {['File name', 'Folder', 'Version', 'Method'].map(h => (
                  <Text key={h} style={[styles.th, { flex: h === 'File name' ? 3 : h === 'Folder' ? 2 : 1 }]}>{h}</Text>
                ))}
              </View>
              {pFiles.slice(0, 40).map((f, i) => (
                <View key={i} style={styles.tableRow}>
                  <Text style={[styles.td, { flex: 3, fontFamily: 'Courier' }]}>{f.file_name}</Text>
                  <Text style={[styles.td, { flex: 2, color: '#666', fontSize: 8 }]}>{f.folder_path ?? '—'}</Text>
                  <Text style={[styles.td, { flex: 1, color: '#c00' }]}>{f.revit_version}</Text>
                  <Text style={[styles.td, { flex: 1, color: '#888', fontSize: 8 }]}>{f.detection_method ?? '—'}</Text>
                </View>
              ))}
              {pFiles.length > 40 && (
                <Text style={{ fontSize: 8, color: '#666', padding: 4 }}>
                  … and {pFiles.length - 40} more files not shown.
                </Text>
              )}
            </View>
          </Page>
        );
      })}

      {/* Appendix */}
      <Page size="A4" style={styles.page}>
        <Text style={styles.sectionTitle}>Appendix — Methodology</Text>
        <Text style={{ lineHeight: 1.6, marginBottom: 8 }}>
          Version detection uses a 4-tier fallback chain:
        </Text>
        <Text style={{ lineHeight: 1.6, marginLeft: 12, marginBottom: 4 }}>
          T0 (dm_extension): For cloud workshared models, the Revit version is embedded in the
          Autodesk Data Management API item version extension data at zero extra cost.
        </Text>
        <Text style={{ lineHeight: 1.6, marginLeft: 12, marginBottom: 4 }}>
          T1 (manifest): For translated models, the version appears in the Model Derivative manifest.
        </Text>
        <Text style={{ lineHeight: 1.6, marginLeft: 12, marginBottom: 4 }}>
          T2 (binary_header): For pre-2024 files, parsing the OLE2 file header reveals the version string.
          Not reliable for Revit 2024+.
        </Text>
        <Text style={{ lineHeight: 1.6, marginLeft: 12, marginBottom: 8 }}>
          T3 (unknown): Files that exhaust all methods are conservatively treated as at-risk and flagged
          for manual review.
        </Text>
        <Text style={{ lineHeight: 1.6 }}>
          Priority score formula: weighted combination of file recency (×3), member count normalized
          hub-wide (×2), and at-risk file count normalized hub-wide (×1), scaled 0–100.
        </Text>

        <Text style={styles.footerText}>
          Revit C4R Scanner — self-hosted open source tool.
          All data stored in your own Supabase instance. No data shared with third parties.
        </Text>
      </Page>
    </Document>
  );
}
